version: '3.9'

services:
  face-recognition-app:
    build: ./
    command: ./wait-for-postgres.sh db ./face-recognition-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - host=db
      - DB_PASSWORD=qwerty
      - API_SECRET=yoursecretstring
      - TOKEN_HOUR_LIFESPAN=1

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=utp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"